// export const ADD_CONTACT = 'ADD_CONTACT';
// export const DELETE_CONTACT = 'DELETE_CONTACT';
// export const SET_CURRENT = 'SET_CURRENT';
// export const CLEAR_CURRENT = 'CLEAR_CURRENT';
// export const UPDATE_CONTACT = 'UPDATE_CONTACT';
// export const FILTER_CONTACTS = 'FILTER_CONTACTS';
// export const CLEAR_FILTER = 'CLEAR_FILTER';
// export const SET_ALERT = 'SET_ALERT';
// export const REMOVE_ALERT = 'REMOVE_ALERT';

const ActionTypes = {
  ADD_CONTACT: 'ADD_CONTACT',
  DELETE_CONTACT: 'DELETE_CONTACT',
  SET_CURRENT: 'SET_CURRENT',
  CLEAR_CURRENT: 'CLEAR_CURRENT',
  UPDATE_CONTACT: 'UPDATE_CONTACT',
  FILTER_CONTACTS: 'FILTER_CONTACTS',
  CLEAR_FILTER: 'CLEAR_FILTER',
  SET_ALERT: 'SET_ALERT',
  REMOVE_ALERT: 'REMOVE_ALERT',
};

export default ActionTypes;
